# Generated by Django 3.2.6 on 2021-08-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file_1',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
