# Generated by Django 3.2.6 on 2021-08-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0004_alter_photo_file_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file_1',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
